#Utilizar Adventure para estilizar as mensagens! (traduzir para inglês)
#Utilizar o Minecraft Item para definir o Material de Craft!

Backpacks:
  example_backpack: #ID of Backpack (explicar que precisa ser sneak_case e colocar o link de explicação)
    name: '<grey>Example Backpack' #Name of Item
    lore: #Lore of Item
      - ''
      - 'Example Backpack'
      - ''
    rows: 1 #Número de Linhas de armazenamento
    craft:
      shape:
        - 'CCC'
        - 'C C'
        - 'CCC'
      items:
        C: LEATHER
  example2_backpack: #ID of Backpack (explicar que precisa ser sneak_case e colocar o link de explicação)
    name: '<grey>Example2 Backpack' #Name of Item
    lore: #Lore of Item
      - ''
      - 'Example2 Backpack'
      - ''
    rows: 1 #Número de Linhas de armazenamento
    craft:
      shape:
        - 'CCC'
        - 'C$C'
        - 'CCC'
      items:
        C: LEATHER
        $: example_backpack