#To decorate the texts you need to use AdventureAPI MiniMessages! (Wiki: https://docs.advntr.dev/minimessage/index.html)
#To define the materials for crafting, you must follow the updated item pattern! Example: 'LEATHER' 'STONE' 'DIAMOND'.
#To define a backpack when creating, use the special character '$' and in the list of 'items' pass the ID of that backpack as a parameter!

#List of Placeholders:
# - %permission% = command permission
# - %backpack% = backpack ID param
# - %backpack_name% = backpack name
# - %backpack_rows% = backpack rows number
# - %backpack_slots% = backpack slots number

Permission: 'powerfulbackpacks.use' #If this field is not filled in, the permission will be "powerfullbackpacks.use"

Messages:
  dont_have_permission: '<red>You do not have Permission! (%permission%)'
  not_found: "<red>Backpack was not found! (%backpack%)"
  give_command_usage: '<yellow>Use: /givebackpack <backpack_id>'
  give_command_success: '<green>Backpack %backpack_name% received Successfully!'
  list_command_message: '<green>List of Backpacks:'
  list_command_items_message: '<green> - %backpack_name% (%backpack%)' #Only command with placeholders!

Backpacks:
  basic_backpack: #ID of Backpack (use sneak_case in the backpack identifier!)
    name: '<grey>Basic Backpack' #Name of Item
    lore: #Lore of Item
      - ''
      - '<grey>Its a Basic Backpack'
      - '<grey>Rows: <bold><gold>%backpack_rows%'
      - '<grey>Slots: <bold><gold>%backpack_slots%'
      - ''
    rows: 1 #Number of Rows
    craft: #Craft Struct
      shape: #Shape of Recipe
        - 'LLL'
        - 'L L'
        - 'LLL'
      items: #Items in Recipe
        L: 'LEATHER'
  reinforced_backpack:
    name: '<grey>Reinforced Backpack'
    lore:
      - ''
      - '<grey>Its a Reinforced Backpack'
      - '<grey>Rows: <bold><gold>%backpack_rows%'
      - '<grey>Slots: <bold><gold>%backpack_slots%'
      - ''
    rows: 2
    craft:
      shape:
        - 'III'
        - 'I$I'
        - 'III'
      items:
        I: 'IRON_INGOT'
        $: 'basic_backpack'